name: 🛠 Bug report
description: Create a report to help us improve our package
assignees:
  - "shawkidiurnal"
labels:
  - "bug"
title: "[Bug]:"
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Write a clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: Write a clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Attachments
      description: If applicable, add attachments to help explain your problem.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
