name: ✨ Feature request
description: Suggest an idea or feature for our package
assignees:
  - "shawkidiurnal"
labels:
  - "enhancement"
title: "[Feature]:"
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: Write a clear and concise description of what the problem is.
  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: Write a clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: Write a clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
