name: Releases

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: macos-11
    strategy:
      matrix:
        node: [16]

    steps:
      - name: Checkout and scan repository
        uses: actions/checkout@v2
      - name: Setup and use Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install semantic-release dependencies
        run: npm install @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git conventional-changelog-eslint -D -E
      - name: Release using semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
